### PR TITLE
Replace f32 usage with Decimal

### LINKED ISSUE #109: Avoid f32 fields for representing quantities like money and meter values
Unfortunately, the interpretation of the JSON schema number type here is `f32`. This is not correct due to the potential loss of fractional data. This becomes very important with `SampledValueType` and its `value` field, which represents a metering value. Inaccurate conveyancing of meter values can lead to incorrect billing calculations.

Section 2.1.3 of the OCPP v2.0.1 spec, Primitive Datatypes, declares the following:

_For data being reported by the Charging Station, the full resolution of the source data must be preserved. The decimal sent towards the Charging Station SHALL NOT have more than six decimal places._

I'd suggest replacing most occurences of `f32` with `Decimal` per https://crates.io/crates/fpdec.

I'm happy to raise a PR if there's agreement here.

### PR DESCRIPTION
**Pull request by huntc**
Decimal is now used to retain decimal accuracy. As per the requirements of the OCPP specification.

Fixes #109

### CODE REVIEW

**Review by tommymalmqvist — APPROVED** [review]
lgtm

**Comment by tommymalmqvist** [comment]
Fixes #109

**Comment by huntc** [comment]
Thanks for reviewing and merging!

**Comment by tommymalmqvist** [comment]
> Thanks for reviewing and merging!

Released v1.0.5 now, thank you too @huntc

**Pull request merged**
